### ISSUE TITLE
Null Pointer

### ISSUE THREAD

**Issue by Notlucky101** [alexandsr/BellsAndWhistlesMod#14]
Minecraft 1.20.1 
Bell and Whistles v0.4.01(Forge)
Forge V47.2.0

[crash-2023-11-06_17.24.57-client.txt](https://github.com/sudolev/BellsAndWhistlesMod/files/13274482/crash-2023-11-06_17.24.57-client.txt)

**Comment by a0ax** [comment]
Is this still causing you issues or is it fixed?
