### ISSUE TITLE
Brass and copper steps

### ISSUE THREAD

**Issue by MrLixam** [alexandsr/BellsAndWhistlesMod#15]
For some reason, the brass and copper steps have no item in their recipe, can make infinite brass steps

version: 1.19.2, latest fabric loader for this version

mods:
 alternate-current-mc1.19-1.7.0
 appleskin-fabric-mc1.19-2.4.1
 architectury-6.5.85-fabric
 badpackets-fabric-0.2.2
 bclib-2.1.7
 bellsandwhistles-0.4.1+1.19.2-5
 BetterAdvancements-Fabric-1.19.2-0.2.2.142
 better-end-2.1.6
 better-nether-7.1.4
 cloth-config-8.3.103-fabric
 Clumps-fabric-1.19.2-9.0.0+14
 connectivity-fabric-1.19.2-4.5
 Controlling-fabric-1.19.2-10.0+7
 create_enchantment_industry-1.0.1.b
 createaddition-fabric+1.19.2-20230723a
 createbigcannons-fabric-1.19.2-0.5.2.a
 createchunkloading-1.5.1-fabric
 create-fabric-0.5.1-c-build.1160+mc1.19.2
 creategoggles-1.19.2-0.5.5.d-[FABRIC]
 createoreexcavation-fabric-1.19-1.2.1
 Croptopia-1.19.2-FABRIC-2.2.2
 cullleaves-fabric-3.0.1
 cupboard-fabric-1.19.2-2.0
 dark-loading-screen-1.6.12
 Debugify-2.8.0
 deepslatecutting-fabric-1.5.0
 delightful-creators-1.1.7
 diggusmaximus-1.5.8-1.19
 dynamic-fps-3.2.1+minecraft-1.19.0
 entityculling-fabric-1.6.1-mc1.19.2
 expandeddelight-0.2.5
 expandeddelight-0.2.5.2
 expandedstorage-8.3.4+1.19.2-fabric
 extra_thicc_packets-1.0
 fabric-api-0.76.1+1.19.2
 fabric-language-kotlin-1.10.10+kotlin.1.9.10
 fallingleaves-1.13.0+1.19.2
 FallingTree-1.19.2-3.10.0
 farmers-delight-fabric-mc1.19-1.19.2-1.3.10.1
 farmersknives-2.4.1
 ferritecore-5.0.3-fabric
 ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric
 geckolib-fabric-1.19-3.1.40
 indium-1.0.9+mc1.19.2
 IngredientExtensionAPI-fabric-1.19.2-3.0.6
 InventorySorter-1.8.10-1.19
 krypton-0.2.1
 lazydfu-0.1.3
 lithium-fabric-mc1.19.2-0.11.1
 lunade-fastanim-1.5.6
 memoryleakfix-fabric-1.17+-1.0.0
 MouseTweaks-fabric-mc1.19-2.22
 opac-fabric-create-support-1.3.0
 open-parties-and-claims-fabric-1.19.2-0.19.3
 Origins-1.19.2-1.7.1
 owo-lib-0.8.5+1.19
 Patchouli-1.19.2-77-FABRIC
 reeses_sodium_options-1.6.4+mc1.19.2-build.93
 rer-2.6.0
 rhino-fabric-1902.2.2-build.272
 RoughlyEnoughItems-9.1.657
 RoughlyEnoughLootTables-1.19-1.0
 RoughlyEnoughProfessions-fabric-1.19.2-1.1.4
 servercore-1.3.3-1.19.2
 sliceanddice-fabric-2.3.2
 smoke-suppression-1.0.13+MC1.19-1.19.2
 smoothchunk-fabric-1.19.2-3.2
 sodium-extra-0.4.16+mc1.19.2-build.90
 sodium-fabric-mc1.19.2-0.4.4+build.18
 spark-1.10.37-fabric
 starlight-1.1.1+fabric.ae22326
 Steam_Rails-1.5.1+fabric-mc1.19.2
 TerraBlender-fabric-1.19.2-2.0.1.136
 toms_storage_fabric-1.19-1.5.9
 vanilla-hammers-3.5.0-1.19.2
 wthit-fabric-5.19.0
 Xaeros_Minimap_23.8.2_Fabric_1.19.1
 XaerosWorldMap_1.34.1_Fabric_1.19.1
 YetAnotherConfigLib-2.2.0-for-1.19.2
 youre-in-grave-danger-1.4.9
 Zoomify-2.9.0
 
 how to recreate: start a world, make a crafting table, put and remove an item from the table, and you can make some brass steps, you can also check the recipe, there is no items needed to make it

**Comment by SunkenHero** [comment]
I got the same problem...

**Comment by a0ax** [comment]
Working on it

**Comment by a0ax** [comment]
Fixed in release v0.4.2, out now for fabric and quilt and all that. Thanks so much for the issue!

**Comment by a0ax** [comment]
It's under manual review on curseforge for some reason, available on Modrinth and Github though.

**Comment by SunkenHero** [comment]
Thank you very much!
