### ISSUE TITLE
Mechanical saw recipes overwrite shaft recipe

### ISSUE THREAD

**Issue by jusipat** [alexandsr/BellsAndWhistlesMod#17]
Hi, using a mechanical saw I've encountered a problem where the the output is cycled between all of the below blocks in the screenshot:
![image](https://github.com/sudolev/BellsAndWhistlesMod/assets/60302563/11704038-a426-46f6-8125-faf90a5a36d2)

I am attempting to cut shafts from andesite alloy, but I am instead getting a random assortment of decorative blocks when cutting andesite alloy as shown below:
![image](https://github.com/sudolev/BellsAndWhistlesMod/assets/60302563/e240ae54-3122-4b74-b56b-ddf4f3dc5ac9)

I am unsure if there is a mod incompatibility somewhere or if this is an issue with this mod, please let me know if you have seen anything like this before.

**Comment by jusipat** [comment]
I disregarded item filters, my bad.

**Comment by a0ax** [comment]
You're good, don't worry about it. Glad you figured it out.
