### ISSUE TITLE
Error on build (Registry.register)

### ISSUE THREAD

**Issue by ThomasDubuis** [alexandsr/BellsAndWhistlesMod#18]
I have clone the repo and switch to the branch 1.20.1-fabric.
When i run the Minecraft Client configuration I have this error :
`15:12:34: Executing ':classes'...

Starting Gradle Daemon...
Gradle Daemon started in 504 ms

> Configure project :
Fabric Loom: 1.4.4

> Task :compileJava FAILED
/Users/thomasdubuis/Downloads/BellsAndWhistlesMod/src/main/java/com/sudolev/bellsandwhistles/content/CBWBlocks.java:108: error: no suitable method found for register(ResourceKey<Registry<Block>>,ResourceLocation,Block)
		return Registry.register(Registries.BLOCK, new ResourceLocation(BellsAndWhistles.ID, name), block);
		               ^
    method Registry.<T#1>register(Registry<? super T#1>,String,T#1) is not applicable
      (cannot infer type-variable(s) T#1
        (argument mismatch; ResourceKey<Registry<Block>> cannot be converted to Registry<? super T#1>))
    method Registry.<V#1,T#2>register(Registry<V#1>,ResourceLocation,T#2) is not applicable
      (cannot infer type-variable(s) V#1,T#2
        (argument mismatch; ResourceKey<Registry<Block>> cannot be converted to Registry<V#1>))
    method Registry.<V#2,T#3>register(Registry<V#2>,ResourceKey<V#2>,T#3) is not applicable
      (cannot infer type-variable(s) V#2,T#3
        (argument mismatch; ResourceKey<Registry<Block>> cannot be converted to Registry<V#2>))
  where T#1,V#1,T#2,V#2,T#3 are type-variables:
    T#1 extends Object declared in method <T#1>register(Registry<? super T#1>,String,T#1)
    V#1 extends Object declared in method <V#1,T#2>register(Registry<V#1>,ResourceLocation,T#2)
    T#2 extends V#1 declared in method <V#1,T#2>register(Registry<V#1>,ResourceLocation,T#2)
    V#2 extends Object declared in method <V#2,T#3>register(Registry<V#2>,ResourceKey<V#2>,T#3)
    T#3 extends V#2 declared in method <V#2,T#3>register(Registry<V#2>,ResourceKey<V#2>,T#3)
/Users/thomasdubuis/Downloads/BellsAndWhistlesMod/src/main/java/com/sudolev/bellsandwhistles/content/CBWBlocks.java:112: error: no suitable method found for register(ResourceKey<Registry<Item>>,ResourceLocation,BlockItem)
		return Registry.register(Registries.ITEM, new ResourceLocation(BellsAndWhistles.ID, name),
		               ^
    method Registry.<T#1>register(Registry<? super T#1>,String,T#1) is not applicable
      (cannot infer type-variable(s) T#1
        (argument mismatch; ResourceKey<Registry<Item>> cannot be converted to Registry<? super T#1>))
    method Registry.<V#1,T#2>register(Registry<V#1>,ResourceLocation,T#2) is not applicable
      (cannot infer type-variable(s) V#1,T#2
        (argument mismatch; ResourceKey<Registry<Item>> cannot be converted to Registry<V#1>))
    method Registry.<V#2,T#3>register(Registry<V#2>,ResourceKey<V#2>,T#3) is not applicable
      (cannot infer type-variable(s) V#2,T#3
        (argument mismatch; ResourceKey<Registry<Item>> cannot be converted to Registry<V#2>))
  where T#1,V#1,T#2,V#2,T#3 are type-variables:
    T#1 extends Object declared in method <T#1>register(Registry<? super T#1>,String,T#1)
    V#1 extends Object declared in method <V#1,T#2>register(Registry<V#1>,ResourceLocation,T#2)
    T#2 extends V#1 declared in method <V#1,T#2>register(Registry<V#1>,ResourceLocation,T#2)
    V#2 extends Object declared in method <V#2,T#3>register(Registry<V#2>,ResourceKey<V#2>,T#3)
    T#3 extends V#2 declared in method <V#2,T#3>register(Registry<V#2>,ResourceKey<V#2>,T#3)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

BUILD FAILED in 6s
1 actionable task: 1 executed
15:12:40: Execution finished ':classes'.
`

And intelliJ say this : 
<img width="873" alt="image" src="https://github.com/sudolev/BellsAndWhistlesMod/assets/84736237/72737e51-3878-4d61-9705-ad2e98f9e5cf">

**Comment by ThomasDubuis** [comment]
When I change the Registries.BLOCK into BuiltInRegistries.BLOCK like : 
return Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(BellsAndWhistles.ID, name), block); 
The build is good but I have an other error : 
[error.txt](https://github.com/sudolev/BellsAndWhistlesMod/files/13440770/error.txt)

**Comment by a0ax** [comment]
Yes... the fabric 1.20.1 branch is a WIP branch and there are errors. I have some local commits (ones that I haven't pushed) on my machine, too. I'll sit down and try to get a release-ready build going...

**Comment by a0ax** [comment]
Everything should now be fixed. I published a 1.20 fabric version to [Modrinth](https://modrinth.com/mod/bellsandwhistles/version/0.4.4-mc1.20.x-fabric), [Curseforge](https://www.curseforge.com/minecraft/mc-mods/bellsandwhistles/files/4891052), and [Github](https://github.com/sudolev/BellsAndWhistlesMod/releases/tag/v0.4.4).
