### ISSUE TITLE
Conflicts with Smooth Stone Slab stonecutter recipe

### ISSUE THREAD

**Issue by GameBurrow** [alexandsr/BellsAndWhistlesMod#20]
Station platform stonecutter receipe conclicts with vanilla Minecraft Smooth Stone Slab receipe (MC 1.20.1)

![image](https://github.com/sudolev/BellsAndWhistlesMod/assets/4341091/72c3e0a8-f4f2-4a03-bad2-1faa647062ec)
![image](https://github.com/sudolev/BellsAndWhistlesMod/assets/4341091/2436578e-6ee7-47d7-9ad5-408b2db8dbe5)

**Comment by a0ax** [comment]
I know it looks that way in NEI/JEI/whatever, but stonecutter recipes are meant to be like that. In the stonecutter menu, the user can pick between either one.
![image](https://github.com/sudolev/BellsAndWhistlesMod/assets/61996958/46db8b5f-dddf-4c95-85c1-4c106edb8ac8)
