### ISSUE TITLE
Metro windows are uncraftable

### ISSUE THREAD

**Issue by bangetto** [alexandsr/BellsAndWhistlesMod#26]
## Problem
on 1.20.1 fabric metro windows have the same recipe as corrugated metro casing. 

## Potential Solution
make the crafting recipe of metro windows also have a glass pane

**Comment by a0ax** [comment]
Oopsies
Noted, thanks for the issue!

**Comment by bangetto** [comment]
Noticed, that you added a full glass block to the recipe, but the fabric tag doesn't exists.

You used `fabric:glass`, you should use `c:glass_blocks` instead

**Comment by bangetto** [comment]
I think I found the root of the issue, in the recipe you use the tag of `fabric:glass`, which doesn't exists, it should be replaced with `c:glass_blocks`

bc the tag currently in use doesn't exists JEI/EMI probably ignores it, showing the player the recipe of the corrugated metro casing.

**Comment by kkempfer** [comment]
Same issues for 1.19.2. I actually had planned to fix it in my modpack through KubeJS. Good that @bangetto created the ticket. Thank you.

**Comment by bangetto** [comment]
closing, since the pull-request fixing it was merged
