### ISSUE TITLE
Not A Valid Mod File

### ISSUE THREAD

**Issue by orionSquared** [alexandsr/BellsAndWhistlesMod#5]
I've tried installing your mod via both CurseForge and Modrinth and I'm getting the same error. When trying to launch MC, it tells me:
"File bellsandwhistles-v0.2.jar is not a valid mod file"

Unsure of what to do as this is the only file available.

The only mods I have installed are Create and Bells and Whistles.

This is for 1.19.2

**Comment by TheEmeraldAxolotl** [comment]
> I've tried installing your mod via both CurseForge and Modrinth and I'm getting the same error. When trying to launch MC, it tells me: "File bellsandwhistles-v0.2.jar is not a valid mod file"
> 
> Unsure of what to do as this is the only file available.
> 
> The only mods I have installed are Create and Bells and Whistles.
> 
> This is for 1.19.2

I have had the same issue, although I have more mods installed

**Comment by B14nk2** [comment]
happend to me too, the 1.19.2 mod file is broken.

**Comment by mistresskahlan** [comment]
Same here for the 1.19.2 version

**Comment by NightScale5755** [comment]
Well this is a doozy with an easy fix:
* Open the mod jar with 7zip or equivalent.
* Edit the "META-INF/MANIFEST.MF" file.
* Change the line "Implementation-Version: v0.2" to "Implementation-Version: 0.2".

**Comment by a0ax** [comment]
Thanks a ton all of you, I really appreciate it. Fixed now and up on all platforms.
