### ISSUE TITLE
Missing sound for 'bellsandwhistles:koppabavisan'

### ISSUE THREAD

**Issue by Xyphenore** [alexandsr/BellsAndWhistlesMod#6]
**Describe the bug**

The sound is missing for the event 'bellsandwhistles:koppabavisan'.

Warning from the console: 'Missing sound for event: bellsandwhistles:koppabavisan'

**To Reproduce**

- Install the mod.
- Run the game with the output console.
- Create a world
- Warning is printed on console

**Additional context**
- Mod version: 0.1 for 1.20.1
- Forge version: 47.1.47
- Create version: 0.5.1b for 1.20.1

**Comment by a0ax** [comment]
Fixed in the latest version!
