### ISSUE TITLE
Metro Window not breakable

### ISSUE THREAD

**Issue by f0kx** [alexandsr/BellsAndWhistlesMod#7]
Minecraft 1.19.2
Forge 43.2.23
Version 0.4

The New metro Window dont have a Tag for breaking with the wrench or pickaxe.

**Comment by a0ax** [comment]
working on it

**Comment by a0ax** [comment]
Fixed in [v0.4.1](https://github.com/sudoLev/BellsAndWhistlesMod/releases/tag/v0.4.1), which is out now. Thanks for the issue!

**Comment by f0kx** [comment]
thank you that was very fast :P
